config/routes.rb
HealthLetter::Application.routes.draw do

  get 'patient', to: 'patients#show'
  resources :patients
  root to: 'patients#index'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def new
    @patient = Patient.new
  end

  def show 
    @list = ["Psoriasis", "inflammatory bowel disease", "hair loss", "sicca symptoms", "renal disease", "raynaud's", "malar rash or photo sensitivity", "recurrent mouth ulcers", "DVT or PE", "shortness of breath or unexplained chest pain", "iritis"]
    @vasculitis_list = ["bronchial asthma", "increased eosinophil count","nose bleeds","paresthesia","sinusitis"]
    @myositis_list = ["weakness","dysphagia","dysphonia"]
    @fibromyalgia_list = ["non restorative sleep","excessive fatigue","wide spread pain","IBS"]
    @examination_list= ["rash","lymphadenopathy","sclerodactyly","tophi"]
    @symptom_list = ["MCP","PIP","DIP","1st CMC","wrist","elbow","shoulder","hip","knee","ankle","MTP"]
    @family_list = ["SLE","osteoarthritis","rheumatoid arthritis","psoriasis","IBD","uveitis"]
    @patient = params[:name]
    @main_complaint = params[:main_complaint]
    @since_how_long = params[:since_how_long]
    @gender = params[:gender]
    @pains = params[:pains] || []
    if @pains.length > 1 
      @pain_last = @pains.pop
    else
      @pain_last = nil 
    end
    @swellings = params[:swellings] || []
    if @swellings.length > 1 
      @swell_last = @swellings.pop
    else 
      @swell_last = nil
    end
    @morning_stiffness = params[:morning_stiffness]
    @morning_stiffness_duration = params[:morning_stiffness_duration]
    @additional_details = params[:additional_details]
    @diseases = params[:disease] || []
    @non_diseases = @list - @diseases 
    if @diseases.length > 1 
      @diseases_last = @diseases.pop 
    else
      @diseases_last = nil
    end
    if @non_diseases.length > 1
      @non_diseases_last = @non_diseases.pop
    else
      @non_diseases_last = nil
    end
    @pain_options = params[:options] || []
    @vasculitis = params[:vasculitis] || []
    @non_vasculitis = @vasculitis_list - @vasculitis  
    if @non_vasculitis.any? == false 
      @vasculitis_full = true
    end
    if @non_vasculitis.length > 1 
      @non_vasculitis_last = @non_vasculitis.pop
    else
      @non_vasculitis_last= nil
    end
    if @vasculitis.length > 1
      @vasculitis_last = @vasculitis.pop
    else
      @vasculitis_last = nil 
    end
    @myositis = params[:myositis] || []
    @non_myositis = @myositis_list - @myositis
     if @non_myositis.any? == false 
      @myositis_full = true
    end
    if @non_myositis.length > 1
      @non_myositis_last = @non_myositis.pop
    else
      @non_myositis_last = nil
    end
    if @myositis.length > 1
      @myositis_last = @myositis.pop
    else
      @myositis_last = nil
    end
    
    @fibromyalgia = params[:fibromyalgia] || []
    @non_fibromyalgia = @fibromyalgia_list - @fibromyalgia
    if @non_fibromyalgia.any? == false 
      @fibromyalgia_full = true
    end
    if @non_fibromyalgia.length > 1
      @non_fibromyalgia_last = @non_fibromyalgia.pop
    else
      @non_fibromyalgia_last = nil
    end
    if @fibromyalgia.length > 1
      @fibromyalgia_last = @fibromyalgia.pop
    else
      @fibromyalgia_last = nil
    end
    
    @examination = params[:examination] || []
    @non_examination = @examination_list - @examination
    if @non_examination.any? == false 
      @examination_full = true
    end
    if @non_examination.length > 1
      @non_examination_last = @non_examination.pop
    else
      @non_examination_last = nil
    end
    if @examination.length > 1
      @examination_last = @examination.pop
    else
      @examination_last = nil
    end
    @MCP_examination = params[:MCP_examination]
    @MCP_swelling = params[:MCP_swelling]
    @MCP_tenderness = params[:MCP_tenderness]
    @PIP_swelling = params[:PIP_swelling]
    @PIP_tenderness = params[:PIP_tenderness]
    @PIP_examination = params[:PIP_examination]
    @DIP_swelling = params[:DIP_swelling]
    @DIP_tenderness = params[:DIP_tenderness]
    @DIP_examination = params[:DIP_examination]
    @CMC_swelling = params[:CMC_swelling]
    @CMC_tenderness = params[:CMC_tenderness]
    @CMC_examination = params[:CMC_examination] 
    @wrist_swelling = params[:wrist_swelling]
    @wrist_tenderness = params[:wrist_tenderness]
    @wrist_examination = params[:wrist_examination]
    @elbow_swelling = params[:elbow_swelling]
    @elbow_tenderness = params[:elbow_tenderness]
    @elbow_examination = params[:elbow_examination]
    @shoulder_swelling = params[:shoulder_swelling]
    @shoulder_tenderness = params[:shoulder_tenderness]
    @shoulder_examination = params[:shoulder_examination] 
    @knee_swelling = params[:knee_swelling]
    @knee_tenderness = params[:knee_tenderness]
    @knee_examination = params[:knee_examination] 
    @ankle_swelling = params[:ankle_swelling]
    @ankle_tenderness = params[:ankle_tenderness]
    @ankle_examination = params[:ankle_examination]
    @MTP_swelling = params[:MTP_swelling]
    @MTP_tenderness = params[:MTP_tenderness]
    @MTP_examination = params[:MTP_examination] 
    @hip_examination = params[:hip_examination]
    @spine_examination = params[:spine_examination]
    @smoke = params[:smokes]
    @smoke_detail = params[:smoke_detail]
    @alcohol = params[:alcohol]
    @alcohol_detail = params[:alcohol_detail]
    @drugs = params[:drugs]
    @drug_detail = params[:drug_detail]
    @occupation = params[:occupation]
    
    @family = params[:family] || []
    @non_family = @family_list - @family
    if @non_family.any? == false 
      @family_full = true
    end
    if @family_list.length > 1
      @non_family_last = @non_family.pop
    else
      @non_family_last = nil
    end
    if @family.length > 1
      @family_last = @family.pop
    else
      @family_last = nil
    end
    @family_details = params[:family_details]
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthLetter</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/show.html.erb
<br>
<%= link_to "<button>Back to form</button>".html_safe, patients_path %>
<h1>Patient <%= @patient %></h1>

<p>Main Complaint: <%= @main_complaint %></p>
<p>Duration: <%= @since_how_long %> </p>
<p>Thank you for reffering <% if @gender == "Male" %> Mr <% end %><% if @gender == "Female" %> Ms <% end %>
<%= @patient %> to my office.</p>
<p><% if @pains.any? %><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %> is complaining of pain in <%= @pains.join(" , ") %><% if @pain_last != nil %> and <%= @pain_last %><% end %>.<% end %><% if @swellings.any? %><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %> has noticed swelling in <%= @swellings.join(", ") %><% if @swell_last != nil %>and <%= @swell_last %><% end %>.<% end %></p>

<% if @pain_options != nil %>The symptons are worse <%= @pain_options.first %>.<% end %>

<% if @morning_stiffness != nil %><p><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %><% if @morning_stiffness == "Yes" %> has morning stiffness that can last for <%= @morning_stiffness_duration %>.<% end %><% if @morning_stiffness == "No" %> does not have morning stiffness.<% end %><% end %></p>

<% if @diseases.any? %><p>There is history of <%= @diseases.join(", ") %><% if @diseases_last != nil %> and <%= @diseases_last %><%end%>.<% end %>
<% if @non_diseases.any? %><p> There is no history of <%= @non_diseases.join(", ") %><% if @non_diseases_last != nil %> or <%= @non_diseases_last %><%end%>.<% end %><hr>

</div>

app/views/patients/show.html.erb
<br>
<div class="container">
<%= link_to "<button>Back to form</button>".html_safe, patients_path %>
<h1>Patient <%= @patient %></h1>

<p><strong>Main Complaint: </strong><%= @main_complaint %></p>
<p><strong>Duration: </strong><%= @since_how_long %> </p>
<p>Thank you for referring <% if @gender == "Male" %> Mr <% end %><% if @gender == "Female" %> Ms <% end %>
<%= @patient %> to my office.</p>
<% if @pains.any? %><p><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %> is complaining of pain in <%= @pains.join(", ") %><% if @pain_last != nil %> and <%= @pain_last %><% end %>.<% end %>
<% if @swellings.any? %><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %> has noticed swelling in <%= @swellings.join(", ") %><% if @swell_last != nil %> and <%= @swell_last %><% end %>.<% end %>
<% if @pain_options.any? %>The symptoms are worse <%= @pain_options.first %>.<% end %>
<% if @morning_stiffness != nil %><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %><% if @morning_stiffness == "Yes" %> has morning stiffness that can last for <%= @morning_stiffness_duration %> minutes.<% end %><% if @morning_stiffness == "No" %> does not have morning stiffness.<% end %></p><% end %>
<p><%= @additional_details %></p>
<% if @diseases.any? %><p>There is history of <%= @diseases.join(" , ") %><% if @diseases_last != nil %> and <%= @diseases_last %><%end%>.<% end %>
<% if @non_diseases.any? %><p> There is no history of <%= @non_diseases.join(", ") %><% if @non_diseases_last != nil %> or <%= @non_diseases_last %><%end%>.<% end %>




<% if @vasculitis_full %> 
<% if @vasculitis.any? %><p><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>
has vasculitis symptoms like <%= @vasculitis.join(", ") %><% if @vasculitis_last != nil %> and <%= @vasculitis_last%><% end %><% end %>
<% elsif @vasculitis.any? %><p><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>
has <%= @vasculitis.join(", ") %><% if @vasculitis_last != nil %> and <%= @vasculitis_last%><% end %>
<% if @non_vasculitis.any? %> but no other vasculitis symptoms like <%= @non_vasculitis.join(", ")%><% if @non_vasculitis_last != nil %> or
<%= @non_vasculitis_last %><% end %><% end %>.</p><% else %> 
<p><% if @non_vasculitis.any? %><p><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>has no vasculitis symptoms like <%= @non_vasculitis.join(", ")%>
<% if @non_vasculitis_last != nil %> or
<%= @non_vasculitis_last %><% end %><% end %>.</p><% end %>





<% if @myositis_full %>
<% if @myositis.any? %><p><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>
has myositis symptoms like <%= @myositis.join(", ")%><% if @myositis_last != nil %> and <%= @myositis_last %><% end %><% end %>
<% elsif @myositis.any? %><p><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>
has <%= @myositis.join(", ")%><% if @myositis_last != nil %> and <%= @myositis_last %><% end %>
<% if @non_myositis.any? %> but no other myositis symptoms like <%= @non_myositis.join(", ")%><% if @non_myositis_last != nil %> or
<%= @non_myositis_last %><% end %><% end %>.</p><% else %>
<% if @non_myositis.any? %><p><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>has no myositis symptoms like <%= @non_myositis.join(", ")%>
<% if @non_myositis_last != nil %> or
<%= @non_myositis_last %><% end %><% end %>.</p><% end %>



<% if @fibromyalgia_full %>
<% if @fibromyalgia.any? %><p><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>
has fibromyalgia symptoms like <%= @fibromyalgia.join(", ")%><% if @fibromyalgia_last != nil %> and <%= @fibromyalgia_last %><% end %>.</p><% end %>
<% elsif @fibromyalgia.any? %><p><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>
has <%= @fibromyalgia.join(", ")%><% if @fibromyalgia_last != nil %> and <%= @fibromyalgia_last %><% end %>
<% if @non_fibromyalgia.any? %> but no other fibromyalgia symptoms like <%= @non_fibromyalgia.join(", ")%><% if @non_fibromyalgia_last != nil %> or
<%= @non_fibromyalgia_last %><% end %><% end %>.</p><% else %>
<% if @non_fibromyalgia.any? %><p><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>has no fibromyalgia symptoms like <%= @non_fibromyalgia.join(", ")%>
<% if @non_fibromyalgia_last != nil %> or
<%= @non_fibromyalgia_last %><% end %><% end %>.</p><% end %>

<p></p><strong>Past medical history:</strong></p>
<p>As above</p>
<p></p><strong>Medication history:</strong></p>
<p>As above</p>

<p><strong>Social History:</strong></p>
<p><% if @occupation != "" %><% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>is a <%= @occupation %>.<%end%>
<% if @smoke != nil %>
<% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %><%= @smoke %> <%= @smoke_detail %> cigarettes per day.
<% else %>
<% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>does not smoke.
<% end %>

<% if @alcohol != nil %>
<% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>consumes <%= @alcohol %> (<%= @alcohol_detail %> per day).
<% else %>
<% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>does not consume alcohol.
<% end %>

<% if @drugs != nil %>
<% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>admits using <%= @drugs %><% if @drug_detail != "" %> (<%= @drug_detail %>)<% end %>.
<% else %>
<% if @gender == "Male" %> He <% end %><% if @gender == "Female" %> She <% end %>does not use recreational drugs.
<% end %></p>

<p><strong>Family History:</strong></p>
<% if @family_full %>
<p>There is family history of <%= @family.join(", ") %><% if @family_last != nil %> and <%= @family_last %><%end%>. <%= @family_details %></p>

<% elsif @family.any? %>
<p>There is family history of <%= @family.join(", ") %><% if @family_last != nil %> and <%= @family_last %><%end%>.<%= @family_details %></p>
<% else %>
<p>There is no family history of <%= @non_family.join(", ") %><% if @non_family_last != nil %> and <%= @non_family_last %><%end%>.<%= @family_details %></p>
<% end %>





<p><strong>Examination:</strong></p>
<% if @examination_full %>
<p>There is <%= @examination.join(", ")%> and <%= @examination_last %>.
<% elsif @examination.any? %><p>There is <%= @examination.join(", ")%><% if @examination_last != nil %> and <%= @examination_last %><% end %>
<% if @non_examination.any? %> and no <%= @non_examination.join(", ")%><% if @non_examination_last != nil %> or
<%= @non_examination_last %><% end %><% end %>.</p><% else %>
<p>There is no <%= @non_examination.join(", ")%><% if @non_examination_last != nil %> or
<%= @non_examination_last %><% end %>.</p>
<% end %>


<p><% if @MCP_swelling.nil? == false %>There is swelling <% if @MCP_tenderness.nil? == false %>and tenderness<% else %>but no tenderness<% end %> of MCP joints<% if @MCP_examination.empty? == false %> (<%= @MCP_examination %>).
<% else%>.<% end %><% elsif @MCP_tenderness.nil? == false %>There is no swelling but there is tenderness of MCP joints<% if @MCP_examination.empty? == false %> (<%= @MCP_examination %>).
<% else%>.<% end %><% elsif @MCP_swelling.nil? %>There is no swelling <% if @MCP_tenderness.nil? %>or tenderness<% end%> of MCP joints.<% if @MCP_examination.empty? == false%> <%= @MCP_examination %>.<% end%><% end %>

<% if @PIP_swelling.nil? == false %>There is swelling <% if @PIP_tenderness.nil? == false %>and tenderness<% else %>but no tenderness<% end %> of PIP joints<% if @PIP_examination.empty? == false %> (<%= @PIP_examination %>).
<% else%>.<% end %><% elsif @PIP_tenderness.nil? == false %>There is no swelling but there is tenderness of PIP joints<% if @PIP_examination.empty? == false %> (<%= @PIP_examination %>).
<% else%>.<% end %><% elsif @PIP_swelling.nil? %>There is no swelling <% if @PIP_tenderness.nil? %>or tenderness<% end%> of PIP joints.<% if @PIP_examination.empty? == false%> <%= @PIP_examination %>.<% end %><% end %>


<% if @DIP_swelling.nil? == false %>There is swelling <% if @DIP_tenderness.nil? == false %>and tenderness<% else %>but no tenderness<% end %> of DIP joints<% if @DIP_examination.empty? == false %> (<%= @DIP_examination %>).
<% else%>.<% end %><% elsif @DIP_tenderness.nil? == false %>There is no swelling but there is tenderness of DIP joints<% if @DIP_examination.empty? == false %> (<%= @DIP_examination %>).
<% else%>.<% end %><% elsif @DIP_swelling.nil?%>There is no swelling <% if @DIP_tenderness.nil? %>or tenderness<% end%> of DIP joints.<% if @DIP_examination.empty? == false%> <%= @DIP_examination %>.<% end %><% end %>


<% if @CMC_swelling.nil? == false %>There is swelling <% if @CMC_tenderness.nil? == false %>and tenderness<% else %>but no tenderness<% end %> of 1st CMC joints<% if @CMC_examination.empty? == false %> (<%= @CMC_examination %>).
<% else%>.<% end %><% elsif @CMC_tenderness.nil? == false %>There is no swelling but there is tenderness of 1st CMC joints<% if @CMC_examination.empty? == false %> (<%= @CMC_examination %>).
<% else%>.<% end %><% elsif @CMC_swelling.nil? %>There is no swelling <% if @CMC_tenderness.nil? %>or tenderness<% end%> of 1st CMC joints.<% if @CMC_examination.empty? == false %> <%= @CMC_examination %>.<% end %><% end %>


<% if @wrist_swelling.nil? == false %>There is swelling <% if @wrist_tenderness.nil? == false %>and tenderness<% else %>but no tenderness<% end %> of wrists<% if @wrist_examination.empty? == false %> (<%= @wrist_examination %>).
<% else%>.<% end %><% elsif @wrist_tenderness.nil? == false %>There is no swelling but there is tenderness of wrists<% if @wrist_examination.empty? == false %> (<%= @wrist_examination %>).
<% else%>.<% end %><% elsif @wrist_swelling.nil? %>There is no swelling <% if @wrist_tenderness.nil? %>or tenderness<% end%> of wrists.<% if @wrist_examination.empty? == false %> <%= @wrist_examination %>.<% end %><% end %>
 

<% if @elbow_swelling.nil? == false %>There is swelling <% if @elbow_tenderness.nil? == false %>and tenderness<% else %>but no tenderness<% end %> of elbows<% if @elbow_examination.empty? == false %> (<%= @elbow_examination %>).
<% else%>.<% end %><% elsif @elbow_tenderness.nil? == false %>There is no swelling but there is tenderness of elbows<% if @elbow_examination.empty? == false %> (<%= @elbow_examination %>).
<% else%>.<% end %><% elsif @elbow_swelling.nil? %>There is no swelling <% if @elbow_tenderness.nil? %>or tenderness<% end%> of elbows.<% if @elbow_examination.empty? == false %> <%= @elbow_examination %>.<% end %><% end %>


<% if @shoulder_swelling.nil? == false %>There is swelling <% if @shoulder_tenderness.nil? == false %>and tenderness<% else %>but no tenderness<% end %> of shoulders<% if @shoulder_examination.empty? == false %> (<%= @shoulder_examination %>).
<% else%>.<% end %><% elsif @shoulder_tenderness.nil? == false %>There is no swelling but there is tenderness of shoulders<% if @shoulder_examination.empty? == false %> (<%= @shoulder_examination %>).
<% else%>.<% end %><% elsif @shoulder_swelling.nil?%>There is no swelling <% if @shoulder_tenderness.nil? %>or tenderness<% end%> of shoulders.<% if @shoulder_examination.empty? == false %> <%= @shoulder_examination %>.<% end %><% end %>


<% if @knee_swelling.nil? == false %>There is swelling <% if @knee_tenderness.nil? == false %>and tenderness<% else %>but no tenderness<% end %> of knees<% if @knee_examination.empty? == false %> (<%= @knee_examination %>).
<% else%>.<% end %><% elsif @knee_tenderness.nil? == false %>There is no swelling but there is tenderness of knees<% if @knee_examination.empty? == false %> (<%= @knee_examination %>).
<% else%>.<% end %><% elsif @knee_swelling.nil? %>There is no swelling <% if @knee_tenderness.nil? %>or tenderness<% end%> of knees.<% if @knee_examination.empty? == false %> <%= @knee_examination %>.<% end %><% end %>


<% if @ankle_swelling.nil? == false %>There is swelling <% if @ankle_tenderness.nil? == false %>and tenderness<% else %>but no tenderness<% end %> of ankles<% if @ankle_examination.empty? == false %> (<%= @ankle_examination %>).
<% else%>.<% end %><% elsif @ankle_tenderness.nil? == false %>There is no swelling but there is tenderness of ankles<% if @ankle_examination.empty? == false %> (<%= @ankle_examination %>).
<% else%>.<% end %><% elsif @ankle_swelling.nil? %>There is no swelling <% if @ankle_tenderness.nil? %>or tenderness<% end%> of ankles.<% if @ankle_examination.empty? == false %> <%= @ankle_examination %>.<% end %><% end %>


<% if @MTP_swelling.nil? == false %>There is swelling <% if @MTP_tenderness.nil? == false %>and tenderness<% else %>but no tenderness<% end %> of MTP joints<% if @MTP_examination.empty? == false %> (<%= @MTP_examination %>).
<% else%>.<% end %><% elsif @MTP_tenderness.nil? == false %>There is no swelling but there is tenderness of MTP joints<% if @MTP_examination.empty? == false %> (<%= @MTP_examination %>).
<% else%>.<% end %><% elsif @MTP_swelling.nil? %>There is no swelling <% if @MTP_tenderness.nil? %>or tenderness<% end%> of MTP joints.<% if @MTP_examination.empty? == false %> <%= @MTP_examination %>.<% end %><% end %>


<% if @hip_examination != "" %>
<%= @hip_examination %>.
<% else %>
Hip examination is normal.
<% end %>

<% if @spine_examination != "" %>
<%= @spine_examination %>.
<% else %>
Spine examination is normal.
<% end %></p>
</div>
<br>
<br>